// SessionMessage.ts - TypeScript types for session_messages table

export type MessageRole = 'user' | 'assistant' | 'system' | 'tool';

/**
 * A single message or tool call within a session.
 * Maps 1:1 to the session_messages table row.
 */
export interface SessionMessage {
  id: string;               // UUID PK
  session_id: string;       // FK → sessions.id
  session_key?: string;     // Denormalized for fast lookup
  ordinal?: number;         // Message order within session
  role: MessageRole;
  content?: string;         // Message text or tool result
  tool_name?: string;       // Populated for role='tool'
  tool_call_id?: string;    // Correlates tool calls <-> results
  thinking?: string;        // Extended thinking content
  tokens_in?: number;
  tokens_out?: number;
  created_at: Date;
  metadata?: SessionMessageMetadata;
}

/**
 * Flexible metadata stored as JSONB.
 * Extend as needed -- all fields optional.
 */
export interface SessionMessageMetadata {
  model?: string;
  cache_read_tokens?: number;
  cache_write_tokens?: number;
  finish_reason?: string;
  stop_sequence?: string;
  latency_ms?: number;
  [key: string]: unknown;
}

/**
 * Input shape for inserting a new message.
 * id and created_at are generated by the DB.
 */
export type NewSessionMessage = Omit<SessionMessage, 'id' | 'created_at'> & {
  created_at?: Date;
};

/**
 * Query filters for fetching messages.
 */
export interface SessionMessageQuery {
  session_id?: string;
  session_key?: string;
  role?: MessageRole;
  tool_name?: string;
  limit?: number;
  offset?: number;
  order?: 'asc' | 'desc';
}

/**
 * Result of a bulk insert operation.
 */
export interface BulkInsertResult {
  inserted: number;
  first_id?: string;
  last_id?: string;
  duration_ms: number;
}
