import { useEffect, useRef, useState } from 'react';
import { CalendarDays, ChevronDown, ChevronUp, ExternalLink, LockKeyhole, Pause, Play, SkipBack, SkipForward, Volume2, VolumeX, X } from 'lucide-react';
import { Link } from 'react-router-dom';
import { authenticatedFetch } from '../utils/auth';
import { createMindscapeAudioLoader } from './mindscapeAudioLoader.mjs';
import './MindscapePanel.css';

const API = import.meta.env.VITE_API_BASE_URL || '/api';
export type MindscapeTrack = { entry_id:string; run_key:string; date:string; title:string|null; visibility:'private'; duration_seconds?:number|null };
type Props={open:boolean;onClose:()=>void};
const fmt=(seconds:number)=>Number.isFinite(seconds)?`${Math.floor(seconds/60)}:${String(Math.floor(seconds%60)).padStart(2,'0')}`:'0:00';
const formatTrackDate=(value:string)=>new Date(`${value.split('T')[0]}T12:00:00`).toLocaleDateString('en-GB',{weekday:'short',day:'numeric',month:'long',year:'numeric'});
const MEDIA_SESSION_ACTIONS: MediaSessionAction[] = ['play','pause','seekbackward','seekforward','seekto','previoustrack','nexttrack'];
const clearMediaPosition = (session: MediaSession) => { try { session.setPositionState(); } catch { /* Position state is optional on older browsers. */ } };

export function MindscapePanel({open,onClose}:Props){
 const [tracks,setTracks]=useState<MindscapeTrack[]>([]),[selected,setSelected]=useState(0),[expanded,setExpanded]=useState(false),[playing,setPlaying]=useState(false),[failed,setFailed]=useState(false),[loading,setLoading]=useState(false),[time,setTime]=useState(0),[duration,setDuration]=useState(0),[muted,setMuted]=useState(false);
 const audio=useRef<HTMLAudioElement>(null),close=useRef<HTMLButtonElement>(null),previousFocus=useRef<HTMLElement|null>(null),source=useRef<string|null>(null),onCloseRef=useRef(onClose);
 const loader=useRef(createMindscapeAudioLoader({fetchAudio:(runKey:string)=>authenticatedFetch(`${API}/journal/mindscape/${encodeURIComponent(runKey)}/audio`),createObjectURL:(blob:Blob)=>URL.createObjectURL(blob),revokeObjectURL:(url:string)=>URL.revokeObjectURL(url)}));
 const revokeSource=()=>{if(source.current){URL.revokeObjectURL(source.current);source.current=null}};

 useEffect(()=>{onCloseRef.current=onClose},[onClose]);
 useEffect(()=>{if(!open)return;previousFocus.current=document.activeElement as HTMLElement;setLoading(true);setFailed(false);authenticatedFetch(`${API}/journal/mindscape?limit=31`).then(r=>r.ok?r.json():Promise.reject()).then(d=>setTracks(d.tracks||[])).catch(()=>setFailed(true)).finally(()=>setLoading(false));setTimeout(()=>close.current?.focus(),0);const key=(e:KeyboardEvent)=>{if(e.key==='Escape')onCloseRef.current();if(e.key==='Tab'){const root=close.current?.closest('[role=dialog]');const nodes=root?.querySelectorAll<HTMLElement>('button:not(:disabled),a[href],input:not(:disabled),[tabindex]:not([tabindex="-1"])');if(!nodes?.length)return;const first=nodes[0],last=nodes[nodes.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}}};document.addEventListener('keydown',key);return()=>{document.removeEventListener('keydown',key);previousFocus.current?.focus()}},[open]);
 useEffect(()=>()=>{loader.current.cancel();audio.current?.pause();revokeSource()},[]);
 const track=tracks[selected];

 async function playRequested(index:number){const requested=tracks[index],el=audio.current;if(!requested||!el)return;loader.current.cancel();el.pause();revokeSource();setSelected(index);setTime(0);setDuration(0);setPlaying(false);setFailed(false);try{const next=await loader.current.load(requested);if(!next)return;source.current=next;el.src=next;el.load();await el.play()}catch{setFailed(true);setPlaying(false)}}
 function select(index:number,play=false){if(play){void playRequested(index);return}loader.current.cancel();audio.current?.pause();revokeSource();setSelected(index);setTime(0);setDuration(0);setPlaying(false);setFailed(false)}
 async function toggle(){const el=audio.current;if(!el||!track)return;if(!el.paused){el.pause();return}if(source.current){await el.play();return}await playRequested(selected)}
 useEffect(()=>{const session=navigator.mediaSession;if(!track||!session||typeof MediaMetadata==='undefined')return;session.metadata=new MediaMetadata({title:track.title||'Daily Mindscape',artist:'Daily Mindscape',album:'Private journal soundscape'});const seek=(delta:number)=>{const el=audio.current;if(!el)return;const max=Number.isFinite(el.duration)?el.duration:Number.POSITIVE_INFINITY;el.currentTime=Math.max(0,Math.min(max,el.currentTime+delta));setTime(el.currentTime)};const seekTo=(seekTime?:number)=>{const el=audio.current;if(!el||seekTime===undefined)return;const max=Number.isFinite(el.duration)?el.duration:Number.POSITIVE_INFINITY;el.currentTime=Math.max(0,Math.min(max,seekTime));setTime(el.currentTime)};const handlers:Partial<Record<MediaSessionAction,MediaSessionActionHandler>>={play:()=>{void toggle()},pause:()=>audio.current?.pause(),seekbackward:()=>seek(-15),seekforward:()=>seek(15),seekto:(details)=>seekTo(details.seekTime),previoustrack:()=>{if(selected<tracks.length-1)select(selected+1,true)},nexttrack:()=>{if(selected>0)select(selected-1,true)}};for(const action of MEDIA_SESSION_ACTIONS){try{session.setActionHandler(action,handlers[action]||null)}catch{/* Unsupported lock-screen action on this browser. */}}return()=>{for(const action of MEDIA_SESSION_ACTIONS){try{session.setActionHandler(action,null)}catch{/* Unsupported lock-screen action on this browser. */}}session.playbackState='none';session.metadata=null;clearMediaPosition(session)}},[track?.run_key,track?.title,selected,tracks]);
 useEffect(()=>{const session=navigator.mediaSession;if(!session)return;session.playbackState=track?(playing?'playing':'paused'):'none'},[playing,track?.run_key]);
 useEffect(()=>{const session=navigator.mediaSession;if(!session||typeof session.setPositionState!=='function')return;if(!Number.isFinite(duration)||duration<=0){clearMediaPosition(session);return}try{session.setPositionState({duration,playbackRate:audio.current?.playbackRate||1,position:Math.max(0,Math.min(duration,time))})}catch{/* Position state is optional on older browsers. */}},[time,duration,track?.run_key]);

 return <><audio ref={audio} preload="none" onPlay={()=>setPlaying(true)} onPause={()=>setPlaying(false)} onTimeUpdate={e=>setTime(e.currentTarget.currentTime)} onDurationChange={e=>setDuration(e.currentTarget.duration||0)} onEnded={()=>{if(selected>0)void playRequested(selected-1);else setPlaying(false)}} />{open&&<div className="journal-overlay" onMouseDown={e=>{if(e.target===e.currentTarget)onClose()}}><section className="mindscape-sheet" role="dialog" aria-modal="true" aria-labelledby="mindscape-title">
  <header className="drawer-heading"><div className="drawer-heading-copy"><span className="drawer-kicker"><LockKeyhole size={14}/> Private listening</span><h2 id="mindscape-title">Daily Mindscape</h2><p>Your journal, translated into a private daily soundscape.</p></div><button ref={close} className="icon-touch" onClick={onClose} aria-label="Close Daily Mindscape player"><X/></button></header>
  {loading?<div className="mindscape-empty" role="status"><span className="mindscape-loader"/>Loading your private playlist…</div>:!track?<div className={`mindscape-empty ${failed?'is-error':''}`} role={failed?'alert':'status'}><MusicEmpty/><strong>{failed?'Playlist unavailable':'No Mindscapes yet'}</strong><span>{failed?'Please try again in a moment.':'Your first private soundscape will appear here.'}</span></div>:<>
   <div className="now-playing"><span className="now-playing-label">{playing?'Now playing':'Ready to play'}</span><div className="compact-player"><button className="play-main" onClick={()=>void toggle()} aria-label={playing?'Pause Daily Mindscape':'Play Daily Mindscape'}>{playing?<Pause/>:<Play/>}</button><div className="track-copy"><strong title={track.title||`Daily Mindscape — ${track.date}`}>{track.title||'Daily Mindscape'}</strong><span><CalendarDays size={14}/>{formatTrackDate(track.date)}</span></div><div className="player-transport"><button className="icon-touch" disabled={selected===tracks.length-1} onClick={()=>select(selected+1)} aria-label="Previous song"><SkipBack/></button><button className="icon-touch" disabled={selected===0} onClick={()=>select(selected-1)} aria-label="Next song"><SkipForward/></button><button className="icon-touch" onClick={()=>{if(audio.current)audio.current.muted=!muted;setMuted(!muted)}} aria-label={muted?'Unmute':'Mute'}>{muted?<VolumeX/>:<Volume2/>}</button></div></div>
   <div className="player-progress"><span>{fmt(time)}</span><input aria-label="Song progress" type="range" min="0" max={duration||0} value={time} onChange={e=>{const v=Number(e.target.value);if(audio.current)audio.current.currentTime=v;setTime(v)}}/><span>{fmt(duration)}</span></div></div>
   {failed&&<p className="mindscape-alert" role="alert">Private audio could not be loaded. No private media details were exposed.</p>}
   <div className="mindscape-actions"><Link className="source-link" to={`/journal/${track.entry_id}`}><ExternalLink size={16}/> Open source entry</Link><button className="playlist-toggle" onClick={()=>setExpanded(!expanded)} aria-expanded={expanded}>{expanded?<ChevronUp/>:<ChevronDown/>}<span>{expanded?'Hide playlist':`View playlist (${tracks.length})`}</span></button></div>
   {expanded&&<div className="mindscape-playlist" role="list" aria-label="Private Daily Mindscape playlist">{tracks.map((item,index)=><div role="listitem" className={index===selected?'playlist-row selected':'playlist-row'} key={`${item.run_key}:${item.entry_id}`}><button type="button" aria-current={index===selected?'true':undefined} onClick={()=>select(index,true)}><span className="playlist-play">{index===selected&&playing?<Pause size={17}/>:<Play size={17}/>}</span><span><strong>{item.title||'Daily Mindscape'}</strong><small>{formatTrackDate(item.date)}</small></span></button><Link to={`/journal/${item.entry_id}`} aria-label={`Open source journal entry for ${item.title||item.date}`}><ExternalLink size={17}/></Link></div>)}</div>}
  </>}
 </section></div>}</>
}
function MusicEmpty(){return <div className="mindscape-empty-icon"><Volume2 size={26}/></div>}
