import fs from 'fs';import os from 'os';import path from 'path';
import { JournalRunService } from '../services/JournalRunService';
const KEY='a'.repeat(32);
function manifest(state='review_ready'){return {state,operation:'historical_media_repair',executor:'Hermes',content_author:'Nim',immutable_inputs:{entry_id:'id',date:'2026-04-10',entry_type:'narrative',source_sha256:'SECRET_HASH'},requested_media:['image','audio','song'],source:{path:'/secret/source'},approval:{note:'private note'},events:[{at:'2026-07-12T00:00:00Z',state,detail:'secret detail'}]};}
describe('JournalRunService',()=>{let root:string;beforeEach(()=>{root=fs.mkdtempSync(path.join(os.tmpdir(),'runs-'));fs.mkdirSync(path.join(root,KEY));fs.writeFileSync(path.join(root,KEY,'manifest.json'),JSON.stringify(manifest()));});afterEach(()=>fs.rmSync(root,{recursive:true,force:true}));
 it('returns a strict safe DTO and sanitized history',async()=>{const s=new JournalRunService(root);const run=await s.get(KEY);expect(run).toMatchObject({key:KEY,date:'2026-04-10',state:'review_ready',availableActions:['approve','reject']});const encoded=JSON.stringify({run,history:await s.history(KEY)});expect(encoded).not.toContain('SECRET_HASH');expect(encoded).not.toContain('/secret');expect(encoded).not.toContain('private note');expect(encoded).not.toContain('secret detail');});
 it('rejects malformed keys and symlink manifests',async()=>{const s=new JournalRunService(root);await expect(s.get('../bad')).rejects.toThrow('invalid run key');const other='b'.repeat(32);fs.mkdirSync(path.join(root,other));fs.symlinkSync(path.join(root,KEY,'manifest.json'),path.join(root,other,'manifest.json'));await expect(s.get(other)).rejects.toThrow('unsafe run manifest');});
 it('executes review with argv rather than a shell string',async()=>{const log=path.join(root,'argv.txt'),fake=path.join(root,'fake');fs.writeFileSync(fake,`#!/bin/sh\nprintf '%s\\n' "$@" > ${log}\n`);fs.chmodSync(fake,0o755);const note='safe; touch /tmp/should-not-exist';const s=new JournalRunService(root,fake,'/unused');await s.review(KEY,'human', 'reject',note);const argv=fs.readFileSync(log,'utf8');expect(argv).toContain(note);expect(fs.existsSync('/tmp/should-not-exist')).toBe(false);});
});
